/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FormulesRouteImport } from './routes/formules'
import { Route as TontinesRouteImport } from './routes/tontines'
import { Route as CatalogueIndexRouteImport } from './routes/catalogue.index'
import { Route as CatalogueSlugRouteImport } from './routes/catalogue.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulesRoute = FormulesRouteImport.update({
  id: '/formules',
  path: '/formules',
  getParentRoute: () => rootRouteImport,
} as any)
const TontinesRoute = TontinesRouteImport.update({
  id: '/tontines',
  path: '/tontines',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueIndexRoute = CatalogueIndexRouteImport.update({
  id: '/catalogue/',
  path: '/catalogue/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueSlugRoute = CatalogueSlugRouteImport.update({
  id: '/catalogue/$slug',
  path: '/catalogue/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/formules': typeof FormulesRoute
  '/tontines': typeof TontinesRoute
  '/catalogue/$slug': typeof CatalogueSlugRoute
  '/catalogue/': typeof CatalogueIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/formules': typeof FormulesRoute
  '/tontines': typeof TontinesRoute
  '/catalogue/$slug': typeof CatalogueSlugRoute
  '/catalogue': typeof CatalogueIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/formules': typeof FormulesRoute
  '/tontines': typeof TontinesRoute
  '/catalogue/$slug': typeof CatalogueSlugRoute
  '/catalogue/': typeof CatalogueIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/formules' | '/tontines' | '/catalogue/$slug' | '/catalogue/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/formules' | '/tontines' | '/catalogue/$slug' | '/catalogue'
  id:
    | '__root__'
    | '/'
    | '/formules'
    | '/tontines'
    | '/catalogue/$slug'
    | '/catalogue/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FormulesRoute: typeof FormulesRoute
  TontinesRoute: typeof TontinesRoute
  CatalogueSlugRoute: typeof CatalogueSlugRoute
  CatalogueIndexRoute: typeof CatalogueIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formules': {
      id: '/formules'
      path: '/formules'
      fullPath: '/formules'
      preLoaderRoute: typeof FormulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tontines': {
      id: '/tontines'
      path: '/tontines'
      fullPath: '/tontines'
      preLoaderRoute: typeof TontinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue/': {
      id: '/catalogue/'
      path: '/catalogue'
      fullPath: '/catalogue/'
      preLoaderRoute: typeof CatalogueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue/$slug': {
      id: '/catalogue/$slug'
      path: '/catalogue/$slug'
      fullPath: '/catalogue/$slug'
      preLoaderRoute: typeof CatalogueSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FormulesRoute: FormulesRoute,
  TontinesRoute: TontinesRoute,
  CatalogueSlugRoute: CatalogueSlugRoute,
  CatalogueIndexRoute: CatalogueIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
