/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FavorisRouteImport } from './routes/favoris'
import { Route as FormulesRouteImport } from './routes/formules'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as TontinesRouteImport } from './routes/tontines'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as CatalogueIndexRouteImport } from './routes/catalogue.index'
import { Route as CatalogueSlugRouteImport } from './routes/catalogue.$slug'
import { Route as PaiementAnnuleRouteImport } from './routes/paiement.annule'
import { Route as PaiementSuccesRouteImport } from './routes/paiement.succes'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminCommandesRouteImport } from './routes/_authenticated/admin/commandes'
import { Route as AuthenticatedAdminFlexRouteImport } from './routes/_authenticated/admin/flex'
import { Route as AuthenticatedAdminLivreursRouteImport } from './routes/_authenticated/admin/livreurs'
import { Route as AuthenticatedAdminPaiementsRouteImport } from './routes/_authenticated/admin/paiements'
import { Route as AuthenticatedAdminParametresRouteImport } from './routes/_authenticated/admin/parametres'
import { Route as AuthenticatedAdminProduitsRouteImport } from './routes/_authenticated/admin/produits'
import { Route as AuthenticatedAdminStoriesRouteImport } from './routes/_authenticated/admin/stories'
import { Route as AuthenticatedAdminTontinesRouteImport } from './routes/_authenticated/admin/tontines'
import { Route as AuthenticatedAdminUtilisateursRouteImport } from './routes/_authenticated/admin/utilisateurs'
import { Route as AuthenticatedCommanderSlugRouteImport } from './routes/_authenticated/commander.$slug'
import { Route as AuthenticatedLivraisonOrderIdRouteImport } from './routes/_authenticated/livraison.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FavorisRoute = FavorisRouteImport.update({
  id: '/favoris',
  path: '/favoris',
  getParentRoute: () => rootRouteImport,
} as any)
const FormulesRoute = FormulesRouteImport.update({
  id: '/formules',
  path: '/formules',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const TontinesRoute = TontinesRouteImport.update({
  id: '/tontines',
  path: '/tontines',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CatalogueIndexRoute = CatalogueIndexRouteImport.update({
  id: '/catalogue/',
  path: '/catalogue/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogueSlugRoute = CatalogueSlugRouteImport.update({
  id: '/catalogue/$slug',
  path: '/catalogue/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PaiementAnnuleRoute = PaiementAnnuleRouteImport.update({
  id: '/paiement/annule',
  path: '/paiement/annule',
  getParentRoute: () => rootRouteImport,
} as any)
const PaiementSuccesRoute = PaiementSuccesRouteImport.update({
  id: '/paiement/succes',
  path: '/paiement/succes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminCommandesRoute =
  AuthenticatedAdminCommandesRouteImport.update({
    id: '/commandes',
    path: '/commandes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminFlexRoute = AuthenticatedAdminFlexRouteImport.update({
  id: '/flex',
  path: '/flex',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminLivreursRoute =
  AuthenticatedAdminLivreursRouteImport.update({
    id: '/livreurs',
    path: '/livreurs',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPaiementsRoute =
  AuthenticatedAdminPaiementsRouteImport.update({
    id: '/paiements',
    path: '/paiements',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminParametresRoute =
  AuthenticatedAdminParametresRouteImport.update({
    id: '/parametres',
    path: '/parametres',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProduitsRoute =
  AuthenticatedAdminProduitsRouteImport.update({
    id: '/produits',
    path: '/produits',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminStoriesRoute =
  AuthenticatedAdminStoriesRouteImport.update({
    id: '/stories',
    path: '/stories',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminTontinesRoute =
  AuthenticatedAdminTontinesRouteImport.update({
    id: '/tontines',
    path: '/tontines',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUtilisateursRoute =
  AuthenticatedAdminUtilisateursRouteImport.update({
    id: '/utilisateurs',
    path: '/utilisateurs',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedCommanderSlugRoute =
  AuthenticatedCommanderSlugRouteImport.update({
    id: '/commander/$slug',
    path: '/commander/$slug',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLivraisonOrderIdRoute =
  AuthenticatedLivraisonOrderIdRouteImport.update({
    id: '/livraison/$orderId',
    path: '/livraison/$orderId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/favoris': typeof FavorisRoute
  '/formules': typeof FormulesRoute
  '/panier': typeof PanierRoute
  '/tontines': typeof TontinesRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/catalogue/$slug': typeof CatalogueSlugRoute
  '/paiement/annule': typeof PaiementAnnuleRoute
  '/paiement/succes': typeof PaiementSuccesRoute
  '/catalogue/': typeof CatalogueIndexRoute
  '/admin/commandes': typeof AuthenticatedAdminCommandesRoute
  '/admin/flex': typeof AuthenticatedAdminFlexRoute
  '/admin/livreurs': typeof AuthenticatedAdminLivreursRoute
  '/admin/paiements': typeof AuthenticatedAdminPaiementsRoute
  '/admin/parametres': typeof AuthenticatedAdminParametresRoute
  '/admin/produits': typeof AuthenticatedAdminProduitsRoute
  '/admin/stories': typeof AuthenticatedAdminStoriesRoute
  '/admin/tontines': typeof AuthenticatedAdminTontinesRoute
  '/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/commander/$slug': typeof AuthenticatedCommanderSlugRoute
  '/livraison/$orderId': typeof AuthenticatedLivraisonOrderIdRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/favoris': typeof FavorisRoute
  '/formules': typeof FormulesRoute
  '/panier': typeof PanierRoute
  '/tontines': typeof TontinesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/catalogue/$slug': typeof CatalogueSlugRoute
  '/paiement/annule': typeof PaiementAnnuleRoute
  '/paiement/succes': typeof PaiementSuccesRoute
  '/catalogue': typeof CatalogueIndexRoute
  '/admin/commandes': typeof AuthenticatedAdminCommandesRoute
  '/admin/flex': typeof AuthenticatedAdminFlexRoute
  '/admin/livreurs': typeof AuthenticatedAdminLivreursRoute
  '/admin/paiements': typeof AuthenticatedAdminPaiementsRoute
  '/admin/parametres': typeof AuthenticatedAdminParametresRoute
  '/admin/produits': typeof AuthenticatedAdminProduitsRoute
  '/admin/stories': typeof AuthenticatedAdminStoriesRoute
  '/admin/tontines': typeof AuthenticatedAdminTontinesRoute
  '/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/commander/$slug': typeof AuthenticatedCommanderSlugRoute
  '/livraison/$orderId': typeof AuthenticatedLivraisonOrderIdRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/favoris': typeof FavorisRoute
  '/formules': typeof FormulesRoute
  '/panier': typeof PanierRoute
  '/tontines': typeof TontinesRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/catalogue/$slug': typeof CatalogueSlugRoute
  '/paiement/annule': typeof PaiementAnnuleRoute
  '/paiement/succes': typeof PaiementSuccesRoute
  '/catalogue/': typeof CatalogueIndexRoute
  '/_authenticated/admin/commandes': typeof AuthenticatedAdminCommandesRoute
  '/_authenticated/admin/flex': typeof AuthenticatedAdminFlexRoute
  '/_authenticated/admin/livreurs': typeof AuthenticatedAdminLivreursRoute
  '/_authenticated/admin/paiements': typeof AuthenticatedAdminPaiementsRoute
  '/_authenticated/admin/parametres': typeof AuthenticatedAdminParametresRoute
  '/_authenticated/admin/produits': typeof AuthenticatedAdminProduitsRoute
  '/_authenticated/admin/stories': typeof AuthenticatedAdminStoriesRoute
  '/_authenticated/admin/tontines': typeof AuthenticatedAdminTontinesRoute
  '/_authenticated/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/_authenticated/commander/$slug': typeof AuthenticatedCommanderSlugRoute
  '/_authenticated/livraison/$orderId': typeof AuthenticatedLivraisonOrderIdRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/favoris'
    | '/formules'
    | '/panier'
    | '/tontines'
    | '/admin'
    | '/dashboard'
    | '/catalogue/$slug'
    | '/paiement/annule'
    | '/paiement/succes'
    | '/catalogue/'
    | '/admin/commandes'
    | '/admin/flex'
    | '/admin/livreurs'
    | '/admin/paiements'
    | '/admin/parametres'
    | '/admin/produits'
    | '/admin/stories'
    | '/admin/tontines'
    | '/admin/utilisateurs'
    | '/commander/$slug'
    | '/livraison/$orderId'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/favoris'
    | '/formules'
    | '/panier'
    | '/tontines'
    | '/dashboard'
    | '/catalogue/$slug'
    | '/paiement/annule'
    | '/paiement/succes'
    | '/catalogue'
    | '/admin/commandes'
    | '/admin/flex'
    | '/admin/livreurs'
    | '/admin/paiements'
    | '/admin/parametres'
    | '/admin/produits'
    | '/admin/stories'
    | '/admin/tontines'
    | '/admin/utilisateurs'
    | '/commander/$slug'
    | '/livraison/$orderId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/favoris'
    | '/formules'
    | '/panier'
    | '/tontines'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/catalogue/$slug'
    | '/paiement/annule'
    | '/paiement/succes'
    | '/catalogue/'
    | '/_authenticated/admin/commandes'
    | '/_authenticated/admin/flex'
    | '/_authenticated/admin/livreurs'
    | '/_authenticated/admin/paiements'
    | '/_authenticated/admin/parametres'
    | '/_authenticated/admin/produits'
    | '/_authenticated/admin/stories'
    | '/_authenticated/admin/tontines'
    | '/_authenticated/admin/utilisateurs'
    | '/_authenticated/commander/$slug'
    | '/_authenticated/livraison/$orderId'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FavorisRoute: typeof FavorisRoute
  FormulesRoute: typeof FormulesRoute
  PanierRoute: typeof PanierRoute
  TontinesRoute: typeof TontinesRoute
  CatalogueSlugRoute: typeof CatalogueSlugRoute
  PaiementAnnuleRoute: typeof PaiementAnnuleRoute
  PaiementSuccesRoute: typeof PaiementSuccesRoute
  CatalogueIndexRoute: typeof CatalogueIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoris': {
      id: '/favoris'
      path: '/favoris'
      fullPath: '/favoris'
      preLoaderRoute: typeof FavorisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formules': {
      id: '/formules'
      path: '/formules'
      fullPath: '/formules'
      preLoaderRoute: typeof FormulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tontines': {
      id: '/tontines'
      path: '/tontines'
      fullPath: '/tontines'
      preLoaderRoute: typeof TontinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/catalogue/': {
      id: '/catalogue/'
      path: '/catalogue'
      fullPath: '/catalogue/'
      preLoaderRoute: typeof CatalogueIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogue/$slug': {
      id: '/catalogue/$slug'
      path: '/catalogue/$slug'
      fullPath: '/catalogue/$slug'
      preLoaderRoute: typeof CatalogueSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paiement/annule': {
      id: '/paiement/annule'
      path: '/paiement/annule'
      fullPath: '/paiement/annule'
      preLoaderRoute: typeof PaiementAnnuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paiement/succes': {
      id: '/paiement/succes'
      path: '/paiement/succes'
      fullPath: '/paiement/succes'
      preLoaderRoute: typeof PaiementSuccesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/commandes': {
      id: '/_authenticated/admin/commandes'
      path: '/commandes'
      fullPath: '/admin/commandes'
      preLoaderRoute: typeof AuthenticatedAdminCommandesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/flex': {
      id: '/_authenticated/admin/flex'
      path: '/flex'
      fullPath: '/admin/flex'
      preLoaderRoute: typeof AuthenticatedAdminFlexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/livreurs': {
      id: '/_authenticated/admin/livreurs'
      path: '/livreurs'
      fullPath: '/admin/livreurs'
      preLoaderRoute: typeof AuthenticatedAdminLivreursRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/paiements': {
      id: '/_authenticated/admin/paiements'
      path: '/paiements'
      fullPath: '/admin/paiements'
      preLoaderRoute: typeof AuthenticatedAdminPaiementsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/parametres': {
      id: '/_authenticated/admin/parametres'
      path: '/parametres'
      fullPath: '/admin/parametres'
      preLoaderRoute: typeof AuthenticatedAdminParametresRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/produits': {
      id: '/_authenticated/admin/produits'
      path: '/produits'
      fullPath: '/admin/produits'
      preLoaderRoute: typeof AuthenticatedAdminProduitsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/stories': {
      id: '/_authenticated/admin/stories'
      path: '/stories'
      fullPath: '/admin/stories'
      preLoaderRoute: typeof AuthenticatedAdminStoriesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/tontines': {
      id: '/_authenticated/admin/tontines'
      path: '/tontines'
      fullPath: '/admin/tontines'
      preLoaderRoute: typeof AuthenticatedAdminTontinesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/utilisateurs': {
      id: '/_authenticated/admin/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/admin/utilisateurs'
      preLoaderRoute: typeof AuthenticatedAdminUtilisateursRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/commander/$slug': {
      id: '/_authenticated/commander/$slug'
      path: '/commander/$slug'
      fullPath: '/commander/$slug'
      preLoaderRoute: typeof AuthenticatedCommanderSlugRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/livraison/$orderId': {
      id: '/_authenticated/livraison/$orderId'
      path: '/livraison/$orderId'
      fullPath: '/livraison/$orderId'
      preLoaderRoute: typeof AuthenticatedLivraisonOrderIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminCommandesRoute: typeof AuthenticatedAdminCommandesRoute
  AuthenticatedAdminFlexRoute: typeof AuthenticatedAdminFlexRoute
  AuthenticatedAdminLivreursRoute: typeof AuthenticatedAdminLivreursRoute
  AuthenticatedAdminPaiementsRoute: typeof AuthenticatedAdminPaiementsRoute
  AuthenticatedAdminParametresRoute: typeof AuthenticatedAdminParametresRoute
  AuthenticatedAdminProduitsRoute: typeof AuthenticatedAdminProduitsRoute
  AuthenticatedAdminStoriesRoute: typeof AuthenticatedAdminStoriesRoute
  AuthenticatedAdminTontinesRoute: typeof AuthenticatedAdminTontinesRoute
  AuthenticatedAdminUtilisateursRoute: typeof AuthenticatedAdminUtilisateursRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminCommandesRoute: AuthenticatedAdminCommandesRoute,
    AuthenticatedAdminFlexRoute: AuthenticatedAdminFlexRoute,
    AuthenticatedAdminLivreursRoute: AuthenticatedAdminLivreursRoute,
    AuthenticatedAdminPaiementsRoute: AuthenticatedAdminPaiementsRoute,
    AuthenticatedAdminParametresRoute: AuthenticatedAdminParametresRoute,
    AuthenticatedAdminProduitsRoute: AuthenticatedAdminProduitsRoute,
    AuthenticatedAdminStoriesRoute: AuthenticatedAdminStoriesRoute,
    AuthenticatedAdminTontinesRoute: AuthenticatedAdminTontinesRoute,
    AuthenticatedAdminUtilisateursRoute: AuthenticatedAdminUtilisateursRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedCommanderSlugRoute: typeof AuthenticatedCommanderSlugRoute
  AuthenticatedLivraisonOrderIdRoute: typeof AuthenticatedLivraisonOrderIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedCommanderSlugRoute: AuthenticatedCommanderSlugRoute,
  AuthenticatedLivraisonOrderIdRoute: AuthenticatedLivraisonOrderIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FavorisRoute: FavorisRoute,
  FormulesRoute: FormulesRoute,
  PanierRoute: PanierRoute,
  TontinesRoute: TontinesRoute,
  CatalogueSlugRoute: CatalogueSlugRoute,
  PaiementAnnuleRoute: PaiementAnnuleRoute,
  PaiementSuccesRoute: PaiementSuccesRoute,
  CatalogueIndexRoute: CatalogueIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
